### ISSUE TITLE
Issue at the IoT Agent tutorial page

### ISSUE THREAD

**Issue by rsisto** [Fiware/tutorials.IoT-Agent#15]
Hi, I've been following the tutorial step by step, now I found that this command:
https://github.com/Fiware/tutorials.IoT-Agent/tree/e871f9cb22580e8540159fd56091fb91be061e29#six-request
Is throwing a 400 error (Bad Request):
```
HTTP/1.1 400 Bad Request
X-Powered-By: Express
Fiware-Correlator: 4a43cf97-96a5-4662-bf60-40383593af34
Content-Type: application/json; charset=utf-8
Content-Length: 255
Date: Mon, 22 Oct 2018 11:30:53 GMT
Connection: keep-alive

{"name":"BAD_REQUEST","message":"Request error connecting to the Context Broker: {\"code\":\"400\",\"reasonPhrase\":\"Bad Request\",\"details\":\"JSON Parse Error: unknown field: /contextRegistrations/contextRegistration/attributes/attribute/isDomain\"}"}
```
Any suggestions? Thanks!

**Comment by jason-fox** [comment]
The issue is due to a breaking change in the code base between the `latest` version of the Orion Docker container and the  `latest` version of the IoT Agent for UltraLight. This is because development of the IoT Agent node library is lagging the changes in Orion.

To get the tutorial working you should update the docker-compose file to use Orion `2.0.0` and the IoT Agent `1.7.0` as shown in the latest commit. This was fixed in e871f9 - please `git pull` the upstream repo to get the latest changes.

As a general rule it is much safer not to use `latest` outside of a pure development environment - this hadn't been done until recently since the release versions for the next FIWARE release had not been fixed.

**Comment by rsisto** [comment]
Thank you Jason for the quick answer!
Excellent, I'll try this first thing tomorrow.

**Comment by rsisto** [comment]
Perfect! this is working fine as you suggest :)
