### ISSUE TITLE
Iot-Agent with NGSI-LD - @context

### ISSUE THREAD

**Issue by MarieluiseOden** [FIWARE/tutorials.IoT-Agent#31]
Hello all,
I have questions regarding the use of the Iot-Agent with NGSI-LD.

I will first explain the use case and then get to my questions. The attached sketch should help in understanding. 

I use the IoT-agent for provisioning data from different sources. Each data source has its own naming of attributes, but also references the same models (URLs). 

In the Context Broker, there should be no difference between the names, the same URLs should be used.

I wanted to create a separate context file for each data source that contains the respective mapping. 

In the docker-compose.yml file of the IoT-agent, IOTA_JSON_LD_CONTEXT can be used to specify a context file to use. This specification is used to register entities in context brokers with the attribute "@ context". 

Two questions came up:

1. is it possible to use more than one context file when deploying via the IoT-Agent? 
If this is not possible, would I need to create a union with each file for the IoT-Agent so that the URL mapping of the different data sources works consistently? Or can I specify a specific context file during provisioning?

2. when I provision and change this file via a web service, this change does not seem to be automatically detected by the IoT-Agent. Is there a way to push this update? 
 
![image](https://user-images.githubusercontent.com/89380467/176671370-d290c99b-5782-4632-ba6f-c8f9ad37c5f0.png)

**Comment by MarieluiseOden** [comment]
Thank you for the answer, this helps me a lot!
I tried it with the specification of more  `@context` files and it works as I need in my use case!

**Comment by jason-fox** [comment]
@SBlechmann asked:

> There is still no opportunity to dynamically reference a context file on device creation, is there?

Correct. And I don't think there are currently any plans to change that. Internally within the IoT Agent there is  no concept of JSON-LD or `@context` .

From the **NGSI-v2** viewpoint: an `@context` attribute is unnecessary, and the provisioning interface strives to be acceptable to both **NGSI-v2** and **NGSI-LD**. 

From the **NGSI-LD** viewpoint, registrations use a fixed `@context`, but more importantly register themselves so that the NGSI-LD context broker is obliged to transform all communications to use that fixed `@context`, this means that the IoT Agent can remain as a lightweight thin client and always use the short names defined in the provisioning. Adding a dynamic `@context` would make IoT Agent processing more complex and slower without gaining much in terms of flexibility.

There already is a workaround for this issue: just run multiple instances of the IoT Agent in parallel each using a fixed `@context`. I know that architecturally Telefónica already do something similar to support multiple payloads (e.g both Ultralight and JSON at the same time) - just run multiple IoT Agents in parallel. It's basically the same issue with the same fix.

**Comment by SBlechmann** [comment]
Thanks Jason,

> From the NGSI-LD viewpoint, registrations use a fixed @context, but more importantly register themselves so that the NGSI-LD context broker is obliged to transform all communications to use that fixed @context, this means that the IoT Agent can remain as a lightweight thin client and always use the short names defined in the provisioning. Adding a dynamic @context would make IoT Agent processing more complex and slower without gaining much in terms of flexibility.

By that I meant that the context i just referred to. Pretty much the same way it is done right now. The IoTA does not hold any context information despite its location and refers to it in the payload. There would only be a need to change the data model accordingly. The actual transformation shall still be done by the context brokers.

Nevertheless, thanks for your time!
I believe the workaround with multiple agents is indeed the best way to go for now.
